services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/Kernel.php'

parameters:
    phoenix_base_url: '%env(PHOENIX_BASE_URL)%'
